# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  classic:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: 5UP3R-D1N
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_skyline: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4
          plugin_languages: yes
          plugin_licenses: yes
          plugin_contributors: yes
          plugin_achievements: yes
          plugin_code: yes
          plugin_achievements_limit: 10
      - uses: actions/checkout@v3
      - uses: ericcornelissen/svgo-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  ternimal:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics.terminal.svg
          user: 5UP3R-D1N
          template: terminal
          base: header, metadata
          config_timezone: Asia/Bangkok
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_threshold: 2%
      - uses: ericcornelissen/svgo-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
